<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resorses\fbd77efb-cf91-44bf-a1f4-9b1ac7516c80.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resorses\fbd77efb-cf91-44bf-a1f4-9b1ac7516c80.jpg" />
  </ItemGroup>

</Project>
