<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resorses\5217769998146199571.png" />
    <None Remove="Resorses\Button_NewTask.jpg" />
    <None Remove="Resorses\cropped.png" />
    <None Remove="Resorses\fbd77efb-cf91-44bf-a1f4-9b1ac7516c80.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Text.Json" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\taskLibrary\taskLibrary.csproj" />
    <ProjectReference Include="..\TodoEntities\TodoEntities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resorses\5217769998146199571.png" />
    <Resource Include="Resorses\Button_NewTask.jpg" />
    <Resource Include="Resorses\cropped.png" />
    <Resource Include="Resorses\fbd77efb-cf91-44bf-a1f4-9b1ac7516c80.jpg" />
  </ItemGroup>

</Project>
